"""
Config Defaults Module
按领域拆分的配置默认值
"""

from .core import SYSTEM_CONFIGS, SYSTEM_SCHEMAS
from .business.trading import TRADING_CONFIGS, TRADING_SCHEMAS
from .business.risk import RISK_CONFIGS, RISK_SCHEMAS
from .business.strategy import STRATEGY_CONFIGS, STRATEGY_SCHEMAS
from .business.market import MARKET_CONFIGS, MARKET_SCHEMAS
from .business.notification import NOTIFICATION_CONFIGS, NOTIFICATION_SCHEMAS
from .business.datasource import DATASOURCE_CONFIGS, DATASOURCE_SCHEMAS
from .index import (
    DEFAULT_CONFIGS,
    CONFIG_SCHEMAS,
    CONFIG_CATEGORIES,
    ALL_SCHEMAS,
)

__all__ = [
    "SYSTEM_CONFIGS",
    "SYSTEM_SCHEMAS",
    "TRADING_CONFIGS",
    "TRADING_SCHEMAS",
    "RISK_CONFIGS",
    "RISK_SCHEMAS",
    "STRATEGY_CONFIGS",
    "STRATEGY_SCHEMAS",
    "MARKET_CONFIGS",
    "MARKET_SCHEMAS",
    "NOTIFICATION_CONFIGS",
    "NOTIFICATION_SCHEMAS",
    "DATASOURCE_CONFIGS",
    "DATASOURCE_SCHEMAS",
    "DEFAULT_CONFIGS",
    "CONFIG_SCHEMAS",
    "CONFIG_CATEGORIES",
    "ALL_SCHEMAS",
]
