"""
Config Index - 合并所有领域配置
"""

from typing import Dict, Any
from infrastructure.config.enums import ConfigCategory

from .core import SYSTEM_CONFIGS, SYSTEM_SCHEMAS
from .business.trading import TRADING_CONFIGS, TRADING_SCHEMAS
from .business.risk import RISK_CONFIGS, RISK_SCHEMAS
from .business.strategy import STRATEGY_CONFIGS, STRATEGY_SCHEMAS
from .business.market import MARKET_CONFIGS, MARKET_SCHEMAS
from .business.notification import NOTIFICATION_CONFIGS, NOTIFICATION_SCHEMAS
from .business.datasource import DATASOURCE_CONFIGS, DATASOURCE_SCHEMAS
from .business.approval import APPROVAL_CONFIGS, APPROVAL_SCHEMAS, SYMBOL_APPROVAL_CONFIGS
from .business.correlation import CORRELATION_CONFIGS, CORRELATION_SCHEMAS
from .infrastructure.logging import LOGGING_CONFIGS, LOG_CONFIG, LOG_LEVELS, LOG_FORMAT
from .infrastructure.monitoring import MONITORING_CONFIGS, SYSTEM_HEALTH_METRICS, TRADING_PERFORMANCE_METRICS, RISK_METRICS
from .infrastructure.cache import CACHE_CONFIGS, CACHE_TTL, CACHE_DB_ALLOCATION, KEY_NAMING_CONVENTION, CACHE_KEY_PATTERNS, DEFAULT_TTL
from .infrastructure.api_gateway import API_GATEWAY_CONFIGS, API_ROUTES, RATE_LIMITS, PERMISSIONS, ERROR_CODES
from .infrastructure.alerting import ALERTING_CONFIGS, ALERT_SEVERITY_CONFIG, ALERT_CATEGORIES, ALL_ALERT_RULES
from .infrastructure.middleware import MIDDLEWARE_CONFIGS, MIDDLEWARE_SCHEMAS, KAFKA_TOPICS, MIDDLEWARE_SERVICE_DEPENDENCIES
from .infrastructure.database import DATABASE_CONFIGS, CLICKHOUSE_CONFIGS, POOL_CONFIGS
from .infrastructure.external_apis import (
    EXCHANGE_REST_APIS, EXCHANGE_WS_APIS, LLM_APIS, NEWS_APIS, MACRO_APIS, ETF_APIS,
    BINANCE_REST_API, BINANCE_WS_URL, OKX_REST_API, OKX_WS_PUBLIC_URL,
    OPENAI_API_URL, ANTHROPIC_API_URL, OLLAMA_API_URL, ODAILY_BASE_URL,
)


DEFAULT_CONFIGS: Dict[str, Any] = {
    **SYSTEM_CONFIGS,
    **TRADING_CONFIGS,
    **RISK_CONFIGS,
    **STRATEGY_CONFIGS,
    **MARKET_CONFIGS,
    **NOTIFICATION_CONFIGS,
    **DATASOURCE_CONFIGS,
    **APPROVAL_CONFIGS,
    **CORRELATION_CONFIGS,
    **LOGGING_CONFIGS,
    **MONITORING_CONFIGS,
    **CACHE_CONFIGS,
    **API_GATEWAY_CONFIGS,
    **ALERTING_CONFIGS,
    **MIDDLEWARE_CONFIGS,
    **DATABASE_CONFIGS,
    **CLICKHOUSE_CONFIGS,
    **POOL_CONFIGS,
}


CONFIG_SCHEMAS: Dict[str, Dict] = {
    **SYSTEM_SCHEMAS,
    **TRADING_SCHEMAS,
    **RISK_SCHEMAS,
    **STRATEGY_SCHEMAS,
    **MARKET_SCHEMAS,
    **NOTIFICATION_SCHEMAS,
    **DATASOURCE_SCHEMAS,
    **APPROVAL_SCHEMAS,
    **CORRELATION_SCHEMAS,
    **MIDDLEWARE_SCHEMAS,
}


ALL_SCHEMAS: Dict[str, Dict] = CONFIG_SCHEMAS


CONFIG_CATEGORIES = {
    ConfigCategory.SYSTEM: list(SYSTEM_SCHEMAS.keys()) if SYSTEM_SCHEMAS else [],
    ConfigCategory.TRADING: list(TRADING_SCHEMAS.keys()) if TRADING_SCHEMAS else [],
    ConfigCategory.RISK: list(RISK_SCHEMAS.keys()) if RISK_SCHEMAS else [],
    ConfigCategory.STRATEGY: list(STRATEGY_SCHEMAS.keys()) if STRATEGY_SCHEMAS else [],
    ConfigCategory.MARKET: list(MARKET_SCHEMAS.keys()) if MARKET_SCHEMAS else [],
    ConfigCategory.NOTIFICATION: list(NOTIFICATION_SCHEMAS.keys()) if NOTIFICATION_SCHEMAS else [],
    ConfigCategory.DATASOURCE: list(DATASOURCE_SCHEMAS.keys()) if DATASOURCE_SCHEMAS else [],
    ConfigCategory.APPROVAL: list(APPROVAL_SCHEMAS.keys()) if APPROVAL_SCHEMAS else [],
    ConfigCategory.LOGGING: list(LOGGING_CONFIGS.keys()),
    ConfigCategory.MONITORING: list(MONITORING_CONFIGS.keys()),
    ConfigCategory.CACHE: list(CACHE_CONFIGS.keys()),
    ConfigCategory.API_GATEWAY: list(API_GATEWAY_CONFIGS.keys()),
    ConfigCategory.ALERTING: list(ALERTING_CONFIGS.keys()),
    ConfigCategory.MIDDLEWARE: list(MIDDLEWARE_CONFIGS.keys()),
}


__all__ = [
    "DEFAULT_CONFIGS",
    "CONFIG_SCHEMAS",
    "CONFIG_CATEGORIES",
    "LOG_CONFIG",
    "LOG_LEVELS",
    "LOG_FORMAT",
    "SYSTEM_HEALTH_METRICS",
    "TRADING_PERFORMANCE_METRICS",
    "RISK_METRICS",
    "CACHE_TTL",
    "CACHE_DB_ALLOCATION",
    "KEY_NAMING_CONVENTION",
    "CACHE_KEY_PATTERNS",
    "DEFAULT_TTL",
    "API_ROUTES",
    "RATE_LIMITS",
    "PERMISSIONS",
    "ERROR_CODES",
    "ALERT_SEVERITY_CONFIG",
    "ALERT_CATEGORIES",
    "ALL_ALERT_RULES",
    "KAFKA_TOPICS",
    "MIDDLEWARE_SERVICE_DEPENDENCIES",
    "SYMBOL_APPROVAL_CONFIGS",
]
