"""
TradeAgent Shared Module
共享模块 - 提供 TDP 协议、State 状态管理、Config 运行时配置

配置系统说明：
- config/ - 静态配置（YAML 文件，部署时确定）
- shared/config/ - 运行时配置（Redis 动态，运行时可修改）
"""

from shared.tdp import (
    TDPFormatter,
    TDPValidator,
    TDPMessageType,
    MessageDirection,
    TDPMeta,
    TDPVersionError,
    TDPValidationError,
    TDPMessageBuilder,
    TDPClient,
    TDPServer,
    TDPPubSub,
    get_tdp_pubsub,
)
from shared.state import (
    StateType,
    SystemMode,
    SystemStatus,
    SystemState,
    MarketState,
    Position,
    Order,
    TradingState,
    RiskState,
    StrategyState,
    PortfolioState,
    StateManager,
    SystemStateManager,
    MarketStateManager,
    PositionStateManager,
    RiskStateManager,
    get_state_manager,
    get_system_state_manager,
    get_market_state_manager,
    get_position_state_manager,
    get_risk_state_manager,
)
from shared.config import (
    ConfigCategory,
    ConfigScope,
    ConfigEntry,
    ConfigVersion,
    ConfigSchema,
    ConfigValidationError,
    ConfigManager,
    StrategyConfigManager,
    UserConfigManager,
    DataSourceConfigManager,
    get_config_manager,
    get_strategy_config_manager,
    get_user_config_manager,
    get_datasource_config_manager,
)

__all__ = [
    "TDPFormatter",
    "TDPValidator",
    "TDPMessageType",
    "MessageDirection",
    "TDPMeta",
    "TDPVersionError",
    "TDPValidationError",
    "TDPMessageBuilder",
    "TDPClient",
    "TDPServer",
    "TDPPubSub",
    "get_tdp_pubsub",
    "StateType",
    "SystemMode",
    "SystemStatus",
    "SystemState",
    "MarketState",
    "Position",
    "Order",
    "TradingState",
    "RiskState",
    "StrategyState",
    "PortfolioState",
    "StateManager",
    "SystemStateManager",
    "MarketStateManager",
    "PositionStateManager",
    "RiskStateManager",
    "get_state_manager",
    "get_system_state_manager",
    "get_market_state_manager",
    "get_position_state_manager",
    "get_risk_state_manager",
    "ConfigCategory",
    "ConfigScope",
    "ConfigEntry",
    "ConfigVersion",
    "ConfigSchema",
    "ConfigValidationError",
    "ConfigManager",
    "StrategyConfigManager",
    "UserConfigManager",
    "DataSourceConfigManager",
    "get_config_manager",
    "get_strategy_config_manager",
    "get_user_config_manager",
    "get_datasource_config_manager",
]
