"""
Database Schemas Index
数据库表结构索引
"""

from .user import USER_SCHEMAS, USER_ROLE_SCHEMAS, API_KEY_SCHEMAS
from .trading import ORDER_SCHEMAS, POSITION_SCHEMAS, TRADE_SCHEMAS, FUND_FLOW_SCHEMAS
from .execution import EXECUTION_POSTGRESQL_SCHEMAS
from .audit import OPERATION_LOG_SCHEMAS, LOGIN_LOG_SCHEMAS, AUDIT_LOG_SCHEMAS
from .system import SYSTEM_CONFIG_SCHEMAS, STRATEGY_CONFIG_SCHEMAS
from .timeseries import KLINE_SCHEMAS, FEATURE_SCHEMAS, FACTOR_SCHEMAS, SIGNAL_SCHEMAS, REGIME_SCHEMAS
from .data_lake import DATA_LAKE_SCHEMAS, DATA_LAKE_TABLE_SCHEMAS, DATA_LAKE_MATERIALIZED_VIEWS

POSTGRESQL_SCHEMAS = {
    **USER_SCHEMAS,
    **USER_ROLE_SCHEMAS,
    **API_KEY_SCHEMAS,
    **ORDER_SCHEMAS,
    **POSITION_SCHEMAS,
    **TRADE_SCHEMAS,
    **FUND_FLOW_SCHEMAS,
    **OPERATION_LOG_SCHEMAS,
    **LOGIN_LOG_SCHEMAS,
    **AUDIT_LOG_SCHEMAS,
    **SYSTEM_CONFIG_SCHEMAS,
    **STRATEGY_CONFIG_SCHEMAS,
    **EXECUTION_POSTGRESQL_SCHEMAS,
}

CLICKHOUSE_SCHEMAS = {
    **KLINE_SCHEMAS,
    **FEATURE_SCHEMAS,
    **FACTOR_SCHEMAS,
    **SIGNAL_SCHEMAS,
    **REGIME_SCHEMAS,
    **DATA_LAKE_SCHEMAS,
}

__all__ = [
    "POSTGRESQL_SCHEMAS",
    "CLICKHOUSE_SCHEMAS",
    "DATA_LAKE_SCHEMAS",
    "DATA_LAKE_TABLE_SCHEMAS",
    "DATA_LAKE_MATERIALIZED_VIEWS",
]